//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzinMesaiTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FazlaMesai
    {
        public int MesaiID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<decimal> Saat { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
