//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzinMesaiTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izin
    {
        public int IzinID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> IzinTurID { get; set; }
        public Nullable<System.DateTime> BaslangicTarih { get; set; }
        public Nullable<System.DateTime> BitisTarih { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<bool> DurumTemp { get; set; }
        public Nullable<bool> DurumBit { get; set; }
    
        public virtual IzinTur IzinTur { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
